#!/bin/bash

# Restore Kognisia via API (No Docker Required)
# Usage: ./scripts/restore-api.sh [TARGET_URL] [TARGET_SERVICE_KEY] [BACKUP_NAME]

set -e

if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]; then
    echo "❌ Usage: ./scripts/restore-api.sh [TARGET_URL] [TARGET_SERVICE_KEY] [BACKUP_NAME]"
    echo ""
    echo "📋 Example:"
    echo "   ./scripts/restore-api.sh https://jjgfethvijznoyljylmi.supabase.co your_key backup_name"
    echo ""
    echo "🎯 Available targets:"
    echo "   sahabat-promil: https://jjgfethvijznoyljylmi.supabase.co"
    echo "   kognisia-dev: https://nrmkkuphbkmakzawkda.supabase.co"
    echo ""
    echo "📁 Available backups:"
    ls -la backups/ 2>/dev/null | grep "^d" | awk '{print "   " $9}' || echo "   No backups found"
    exit 1
fi

TARGET_URL=$1
TARGET_SERVICE_KEY=$2
BACKUP_NAME=$3
BACKUP_DIR="./backups/$BACKUP_NAME"

echo "🔄 Starting API restore process"
echo "🎯 Target URL: $TARGET_URL"
echo "📁 Backup source: $BACKUP_DIR"

# Check if backup exists
if [ ! -d "$BACKUP_DIR" ]; then
    echo "❌ Backup directory not found: $BACKUP_DIR"
    exit 1
fi

# Check backup info
if [ -f "$BACKUP_DIR/backup_info.json" ]; then
    echo "📋 Backup info:"
    cat "$BACKUP_DIR/backup_info.json" | jq '.'
    echo ""
fi

# Test connection to target
echo "🔍 Testing connection to target..."
RESPONSE=$(curl -s -X GET "$TARGET_URL/rest/v1/question_bank?limit=1" \
  -H "apikey: $TARGET_SERVICE_KEY" \
  -H "Authorization: Bearer $TARGET_SERVICE_KEY")

if [ -z "$RESPONSE" ]; then
    echo "❌ Cannot connect to target project. Check URL and SERVICE_ROLE_KEY"
    exit 1
fi

echo "✅ Connection successful"

# Function to restore table
restore_table() {
    local table_name=$1
    local json_file="$BACKUP_DIR/$table_name.json"
    
    if [ ! -f "$json_file" ]; then
        echo "⚠️  File not found: $json_file"
        return
    fi
    
    echo "📥 Restoring $table_name..."
    
    local record_count=$(jq length "$json_file")
    if [ "$record_count" -eq 0 ]; then
        echo "⚠️  No records to restore in $table_name"
        return
    fi
    
    # Process records in batches of 100
    local batch_size=100
    local restored=0
    
    jq -c ".[]" "$json_file" | while read -r record; do
        curl -s -X POST "$TARGET_URL/rest/v1/$table_name" \
            -H "apikey: $TARGET_SERVICE_KEY" \
            -H "Authorization: Bearer $TARGET_SERVICE_KEY" \
            -H "Content-Type: application/json" \
            -H "Prefer: return=minimal" \
            -d "$record" > /dev/null
        
        restored=$((restored + 1))
        
        if [ $((restored % batch_size)) -eq 0 ]; then
            echo "   📊 Progress: $restored/$record_count records"
        fi
    done
    
    echo "✅ $table_name restored: $restored records"
}

# Restore all tables
restore_table "subtests"
restore_table "question_bank"
restore_table "classes"
restore_table "squads"
restore_table "achievements"

# Note: Users and Student Progress need special handling
echo "⚠️  Note: Users and Student Progress require manual migration"
echo "   👥 Users: Export from auth dashboard and import manually"
echo "   📈 Student Progress: May need UUID remapping"

# Create environment file
echo "🔧 Creating environment file..."
cat > ".env.restored" << EOF
# Generated by restore script - $(date)
NEXT_PUBLIC_SUPABASE_URL=$TARGET_URL
SUPABASE_SERVICE_ROLE_KEY=$TARGET_SERVICE_KEY
TARGET_URL=$TARGET_URL
RESTORED_FROM=$BACKUP_NAME
RESTORED_AT=$(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF

echo "✅ Environment file created: .env.restored"
echo "📝 To use: cp .env.restored .env.local"

# Verify restore
echo "🔍 Verifying restore..."
echo "📊 Question bank count:"
curl -s -X GET "$TARGET_URL/rest/v1/question_bank?select=count" \
  -H "apikey: $TARGET_SERVICE_KEY" \
  -H "Authorization: Bearer $TARGET_SERVICE_KEY" | jq '.'

echo "📋 Subtests count:"
curl -s -X GET "$TARGET_URL/rest/v1/subtests?select=count" \
  -H "apikey: $TARGET_SERVICE_KEY" \
  -H "Authorization: Bearer $TARGET_SERVICE_KEY" | jq '.'

echo ""
echo "🎉 API restore completed successfully!"
echo ""
echo "📋 Summary:"
echo "   🎯 Target: $TARGET_URL"
echo "   📁 Source: $BACKUP_NAME"
echo "   🔑 Config: .env.restored"
echo ""
echo "🔄 Next steps:"
echo "   1. Copy environment file: cp .env.restored .env.local"
echo "   2. Update Vercel environment variables"
echo "   3. Test API endpoints"
echo "   4. Deploy application"
echo "   5. Migrate users manually via auth dashboard"
echo ""
echo "🌐 Access dashboard: https://supabase.com/dashboard/project/$(echo $TARGET_URL | sed 's/https:\/\/\([^.]*\).*/\1/')"