#!/bin/bash

# Restore Kognisia Supabase Project
# Usage: ./scripts/restore-kognisia.sh [TARGET_PROJECT_REF] [BACKUP_NAME]

set -e

if [ -z "$1" ] || [ -z "$2" ]; then
    echo "❌ Usage: ./scripts/restore-kognisia.sh [TARGET_PROJECT_REF] [BACKUP_NAME]"
    echo ""
    echo "📋 Available projects:"
    echo "   luioyqrubylvjospgsjx  - kognisia-app (current)"
    echo "   jjgfethvijznoyljylmi  - sahabat-promil"
    echo "   nrmkkuphbkmakzawkda  - kognisia-dev"
    echo ""
    echo "📁 Available backups:"
    ls -la backups/ 2>/dev/null | grep "^d" | awk '{print "   " $9}' || echo "   No backups found"
    exit 1
fi

TARGET_PROJECT=$1
BACKUP_NAME=$2
BACKUP_DIR="./backups/$BACKUP_NAME"

echo "🔄 Starting restore process"
echo "🎯 Target project: $TARGET_PROJECT"
echo "📁 Backup source: $BACKUP_DIR"

# Check if backup exists
if [ ! -d "$BACKUP_DIR" ]; then
    echo "❌ Backup directory not found: $BACKUP_DIR"
    exit 1
fi

# Check backup info
if [ -f "$BACKUP_DIR/backup_info.json" ]; then
    echo "📋 Backup info:"
    cat "$BACKUP_DIR/backup_info.json" | jq '.'
    echo ""
fi

# Get target project URL
case $TARGET_PROJECT in
    "luioyqrubylvjospgsjx")
        TARGET_URL="https://nxlkgjmwujolzqaxsine.supabase.co"
        TARGET_NAME="kognisia-app"
        ;;
    "jjgfethvijznoyljylmi")
        TARGET_URL="https://jjgfethvijznoyljylmi.supabase.co"
        TARGET_NAME="sahabat-promil"
        ;;
    "nrmkkuphbkmakzawkda")
        TARGET_URL="https://nrmkkuphbkmakzawkda.supabase.co"
        TARGET_NAME="kognisia-dev"
        ;;
    *)
        echo "❌ Unknown project reference: $TARGET_PROJECT"
        exit 1
        ;;
esac

echo "🌐 Target URL: $TARGET_URL"
echo "🏷️  Target name: $TARGET_NAME"

# 1. Link to target project
echo "🔗 Linking to target project..."
supabase link --project-ref $TARGET_PROJECT

# 2. Reset target database
echo "🗑️ Resetting target database..."
supabase db reset

# 3. Restore schema
if [ -f "$BACKUP_DIR/schema.sql" ]; then
    echo "🏗️ Restoring schema..."
    supabase db push "$BACKUP_DIR/schema.sql"
fi

# 4. Restore data
if [ -f "$BACKUP_DIR/data.sql" ]; then
    echo "📊 Restoring data..."
    supabase db push "$BACKUP_DIR/data.sql"
fi

# 5. Get target service role key (user will need to provide this)
echo "⚠️  NOTE: You need to provide the SERVICE_ROLE_KEY for target project"
echo "🔑 Get it from: https://supabase.com/dashboard/project/$TARGET_PROJECT/settings/api"
echo ""
read -p "Enter SERVICE_ROLE_KEY for $TARGET_NAME: " TARGET_SERVICE_KEY

if [ -z "$TARGET_SERVICE_KEY" ]; then
    echo "❌ SERVICE_ROLE_KEY is required for data restoration"
    exit 1
fi

# 6. Restore question bank via API
if [ -f "$BACKUP_DIR/question_bank.json" ]; then
    echo "❓ Restoring question bank..."
    
    # Read and process questions in batches
    jq -c '.[]' "$BACKUP_DIR/question_bank.json" | while read -r question; do
        curl -X POST "$TARGET_URL/rest/v1/question_bank" \
            -H "apikey: $TARGET_SERVICE_KEY" \
            -H "Authorization: Bearer $TARGET_SERVICE_KEY" \
            -H "Content-Type: application/json" \
            -H "Prefer: return=minimal" \
            -d "$question"
        echo "✅ Restored question"
    done
fi

# 7. Restore student progress via API
if [ -f "$BACKUP_DIR/student_progress.json" ]; then
    echo "📈 Restoring student progress..."
    
    jq -c '.[]' "$BACKUP_DIR/student_progress.json" | while read -r progress; do
        curl -X POST "$TARGET_URL/rest/v1/student_progress" \
            -H "apikey: $TARGET_SERVICE_KEY" \
            -H "Authorization: Bearer $TARGET_SERVICE_KEY" \
            -H "Content-Type: application/json" \
            -H "Prefer: return=minimal" \
            -d "$progress"
        echo "✅ Restored progress record"
    done
fi

# 8. Restore subtests via API
if [ -f "$BACKUP_DIR/subtests.json" ]; then
    echo "📋 Restoring subtests..."
    
    jq -c '.[]' "$BACKUP_DIR/subtests.json" | while read -r subtest; do
        curl -X POST "$TARGET_URL/rest/v1/subtests" \
            -H "apikey: $TARGET_SERVICE_KEY" \
            -H "Authorization: Bearer $TARGET_SERVICE_KEY" \
            -H "Content-Type: application/json" \
            -H "Prefer: return=minimal" \
            -d "$subtest"
        echo "✅ Restored subtest"
    done
fi

# 9. Update environment variables
echo "🔧 Creating environment file for target project..."
cat > ".env.$TARGET_NAME" << EOF
# Generated by restore script - $(date)
NEXT_PUBLIC_SUPABASE_URL=$TARGET_URL
SUPABASE_SERVICE_ROLE_KEY=$TARGET_SERVICE_KEY
TARGET_PROJECT=$TARGET_PROJECT
TARGET_NAME=$TARGET_NAME
RESTORED_FROM=$BACKUP_NAME
RESTORED_AT=$(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF

echo "✅ Environment file created: .env.$TARGET_NAME"
echo "📝 To use: cp .env.$TARGET_NAME .env.local"

# 10. Verify restore
echo "🔍 Verifying restore..."
supabase db shell --command "SELECT COUNT(*) as total_tables FROM information_schema.tables WHERE table_schema = 'public';" 2>/dev/null || echo "⚠️  Could not verify table count"

supabase db shell --command "SELECT COUNT(*) as total_questions FROM question_bank;" 2>/dev/null || echo "⚠️  Could not verify question count"

echo ""
echo "🎉 Restore completed successfully!"
echo ""
echo "📋 Summary:"
echo "   🎯 Target: $TARGET_NAME ($TARGET_PROJECT)"
echo "   📁 Source: $BACKUP_NAME"
echo "   🔑 Config: .env.$TARGET_NAME"
echo ""
echo "🔄 Next steps:"
echo "   1. Copy environment file: cp .env.$TARGET_NAME .env.local"
echo "   2. Update Vercel environment variables"
echo "   3. Test API endpoints"
echo "   4. Deploy application"
echo ""
echo "🌐 Access dashboard: https://supabase.com/dashboard/project/$TARGET_PROJECT"